In [2]:
import numpy as np

# Array creation + inspection (type, dtype, ndim, size, shape)

In [3]:

arr1 = np.array([15, 16, 15, 17, 16])
print(type(arr1))
print(arr1.dtype)
print(arr1.ndim)
print(arr1.size)
print(arr1.shape)


<class 'numpy.ndarray'>
int64
1
5
(5,)


In [6]:

arr2 = np.array([[36.5, 37.2], [36.8, 38.1], [37.0, 36.9]])
print(type(arr2))
print(arr2.dtype)
print(arr2.ndim)
print(arr2.size)
print(arr2.shape)


<class 'numpy.ndarray'>
float64
2
6
(3, 2)


In [7]:

arr3 = np.array([[[50, 75.5], [60, 80]], [[45.5, 70], [55, 90.5]]])
print(type(arr3))
print(arr3.dtype)
print(arr3.ndim)
print(arr3.size)
print(arr3.shape)


<class 'numpy.ndarray'>
float64
3
8
(2, 2, 2)


# 2) reshape() — normal, -1 auto-dim, 3D

In [8]:

a = np.array([120, 150, 130, 160, 140, 170, 155, 165, 145, 175, 135, 180])
print(a.reshape(3, 4))


[[120 150 130 160]
 [140 170 155 165]
 [145 175 135 180]]


In [9]:

b = np.array([56, 78, 90, 45, 67, 89, 34, 72, 88, 91, 60, 77])
print(b.reshape(-1, 3))   


[[56 78 90]
 [45 67 89]
 [34 72 88]
 [91 60 77]]


In [10]:

c = np.array([30, 32, 31, 29, 33, 30, 25, 27, 26, 24, 28, 27])
print(c.reshape(2, 2, 3))


[[[30 32 31]
  [29 33 30]]

 [[25 27 26]
  [24 28 27]]]


# 3) std() and var()

In [11]:

d1 = np.array([88, 90, 87, 91, 89])
print(d1.std())
print(d1.var())


1.4142135623730951
2.0


In [12]:

d2 = np.array([15000, 90000, 45000, 200000, 30000])
print(d2.std())
print(d2.var())


66887.96603276258
4474000000.0


In [13]:

d3 = np.array([10.01, 10.00, 10.02, 10.01, 10.00])
print(d3.std())
print(d3.var())


0.007483314773547724
5.599999999999762e-05


# 4) eye() and zeros()

In [14]:

print(np.eye(2))   
print(np.eye(3))   
print(np.eye(5))  


[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:

print(np.zeros(5))


[0. 0. 0. 0. 0.]


In [16]:

print(np.zeros((3, 4)))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 5) copy() — independent from original

In [17]:

orig = np.array([100, 250, 300, 450])
copied = orig.copy()
orig[0] = 999   
print(copied)   


[100 250 300 450]


In [18]:

orig2 = np.array([56, 78, 90, 45, 67])
copied2 = orig2.copy()
orig2[0] = 100   
print(copied2)   


[56 78 90 45 67]


In [19]:

orig3 = np.array([25.5, 26.0, 24.8, 27.3])
copied3 = orig3.copy()
orig3[0] = 0.0   
print(copied3)  


[25.5 26.  24.8 27.3]


# 6) sum(axis=0) and sum(axis=1)

In [20]:

mat1 = np.array([[100, 150, 200], [80, 90, 120]])
print(mat1.sum(axis=0))  
print(mat1.sum(axis=1))  


[180 240 320]
[450 290]


In [21]:

mat2 = np.array([[78, 65, 90, 82], [55, 60, 70, 65], [88, 92, 85, 95]])
print(mat2.sum(axis=0))  
print(mat2.sum(axis=1)) 


[221 217 245 242]
[315 250 360]


In [22]:

mat3 = np.array([[12, 8], [20, 15], [5, 3], [18, 22]])
print(mat3.sum(axis=0))  
print(mat3.sum(axis=1)) 


[55 48]
[20 35  8 40]


# 7) ravel() vs flatten() — view vs copy

# ravel() — 3 implementations

In [23]:
# Implementation 1: Classroom seating numbers (2x2 grid)
base1 = np.array([[1, 2], [3, 4]])
r1 = base1.ravel()
r1[0] = 999
print(base1)   # changed — ravel() is a view, linked to original

[[999   2]
 [  3   4]]


In [24]:
# Implementation 2: Product price grid (2 products x 2 warehouses)
base2 = np.array([[500, 750], [300, 620]])
r2 = base2.ravel()
r2[0] = 9999
print(base2)   # changed — same memory as original

[[9999  750]
 [ 300  620]]


In [25]:
# Implementation 3: Temperature readings (2 days x 2 time slots)
base3 = np.array([[22.5, 28.0], [24.1, 29.3]])
r3 = base3.ravel()
r3[0] = 0.0
print(base3)   # changed — ravel() reflects back on original

[[ 0.  28. ]
 [24.1 29.3]]


# flatten() — 3 implementations

In [26]:

base4 = np.array([[1, 2], [3, 4]])
f1 = base4.flatten()
f1[0] = 111
print(base4)


[[1 2]
 [3 4]]


In [27]:
scores = np.array([[85, 90], [78, 92]])   # original marks, safe

temp = scores.flatten()   
temp[0] = 0                

print(scores)   
print(temp)     

[[85 90]
 [78 92]]
[ 0 90 78 92]


In [28]:

marks = np.array([[85, 78], [92, 88], [60, 70]])


all_marks = marks.flatten()
highest = np.sort(all_marks)[-1]   

print(highest)  
print(marks)     

92
[[85 78]
 [92 88]
 [60 70]]


# 8) Boolean masking with & (AND)

In [29]:

data1 = np.array([45, 55, 60, 90, 35, 72, 88, 50])
mask1 = (data1 > 50) & (data1 < 80)
print(data1[mask1])


[55 60 72]


In [30]:

data2 = np.array([4, 15, 22, 7, 30, 9, 16])
mask2 = (data2 % 2 == 0) & (data2 > 10)
print(data2[mask2])


[22 30 16]


In [31]:

data3 = np.array([35, 42, 58, 95, 61, 33, 78])
mask3 = (data3 >= 33) & (data3 != 95)   

print(data3[mask3])

[35 42 58 61 33 78]


# 9) transpose()

In [32]:
t = np.array([[1, 2, 3], [4, 5, 6]])

print(t.transpose())

[[1 4]
 [2 5]
 [3 6]]


In [33]:
t = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print(t.transpose())

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [34]:
temperature = np.array([
    [32, 28, 25],
    [35, 30, 27],
    [31, 29, 24],
    [33, 31, 26]
])

print(temperature.transpose())

[[32 35 31 33]
 [28 30 29 31]
 [25 27 24 26]]


# 10)broadcasting on arrays

In [35]:
roll_numbers = np.array([101, 102, 103, 104, 105])

print(roll_numbers % 2)

[1 0 1 0 1]


In [36]:
marks = np.array([65, 72, 80, 68, 90])

bonus = 5

print(marks + bonus)

[70 77 85 73 95]


In [37]:
prices = np.array([500, 800, 1000, 1500, 2000])

discount = 0.10

print(prices - (prices * discount))

[ 450.  720.  900. 1350. 1800.]


# 11) List repetition vs array broadcasting

In [38]:
py_list = [1, 2, 3]
print(py_list * 3)

np_arr = np.array([1, 2, 3])
print(np_arr * 3)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [39]:
py_list = ["Aman", "Riya", "Siya"]
print(py_list * 2)

np_arr = np.array([10, 20, 30])
print(np_arr * 2)

['Aman', 'Riya', 'Siya', 'Aman', 'Riya', 'Siya']
[20 40 60]


In [40]:
py_list = [2, 5, 3]
print(py_list * 3)

np_arr = np.array([2, 5, 3])
print(np_arr * 3)

[2, 5, 3, 2, 5, 3, 2, 5, 3]
[ 6 15  9]


# 12) Boolean masking with ~ (NOT / inverse)

In [41]:
marks = np.array([35, 72, 28, 90, 45, 20])

mask = (marks >= 40)

print(marks[mask])     # Passed
print(marks[~mask])    # Failed

[72 90 45]
[35 28 20]


In [42]:
prices = np.array([500, 1200, 800, 2500, 1500, 300])

mask = (prices >= 1000)

print(prices[mask])     # ₹1000 or more
print(prices[~mask])    # Below ₹1000

[1200 2500 1500]
[500 800 300]


In [43]:
temperature = np.array([25, 32, 38, 29, 41, 27])

mask = (temperature >= 35)

print(temperature[mask])     # Hot
print(temperature[~mask])    # Not hot

[38 41]
[25 32 29 27]


# 13) Range masking with & (between two values)


In [44]:
numbers = np.array([10, 15, 20, 25, 30, 35, 40])

mask = (numbers % 2 == 0) & (numbers % 5 == 0)

print(numbers[mask])

[10 20 30 40]


In [45]:
ages = np.array([18, 20, 18, 22, 21, 18])

mask = (ages == 18) & (ages % 2 == 0)

print(ages[mask])

[18 18 18]


In [46]:
numbers = np.array([12, 15, 20, 30, 45, 50, 60])

mask = (numbers % 3 == 0) & (numbers % 5 == 0)

print(numbers[mask])

[15 30 45 60]


# 14) np.select() — single condition


In [47]:
age = np.array([12, 18, 15, 21, 16])

print(np.select([age >= 18], ["Adult"], default="Minor"))

['Minor' 'Adult' 'Minor' 'Adult' 'Minor']


In [48]:
attendance = np.array([65, 80, 75, 90, 55])

print(np.select([attendance >= 75], ["Eligible"], default="Not Eligible"))

['Not Eligible' 'Eligible' 'Eligible' 'Eligible' 'Not Eligible']


In [49]:
numbers = np.array([10, -5, 8, -2, 15])

print(np.select([numbers >= 0], ["Positive"], default="Negative"))

['Positive' 'Negative' 'Positive' 'Negative' 'Positive']


# 15) np.select() — multiple conditions with default


In [50]:
marks = np.array([95, 82, 76, 68, 55, 43, 31, 89, 72, 60, 97, 25])

cond = [
    (marks >= 80) & (marks <= 100),
    (marks >= 60) & (marks < 80)
]

choice = ["A Grade", "B Grade"]

print(np.select(cond, choice, default="C Grade"))

['A Grade' 'A Grade' 'B Grade' 'B Grade' 'C Grade' 'C Grade' 'C Grade'
 'A Grade' 'B Grade' 'B Grade' 'A Grade' 'C Grade']


In [51]:
experience = np.array([0, 1, 2, 3, 4, 5, 6, 8, 10, 2, 7, 12])

cond = [
    (experience >= 3) & (experience <= 5),
    (experience > 5) & (experience <= 10)
]

choice = ["Mid-Level", "Senior"]

print(np.select(cond, choice, default="Fresher"))

['Fresher' 'Fresher' 'Fresher' 'Mid-Level' 'Mid-Level' 'Mid-Level'
 'Senior' 'Senior' 'Senior' 'Fresher' 'Senior' 'Fresher']


In [52]:
orders = np.array([
    350, 600, 850, 1200, 1500, 1800,
    2200, 750, 950, 1300, 2500, 450
])

cond = [
    (orders >= 500) & (orders <= 999),
    (orders >= 1000) & (orders <= 1999)
]

choice = ["5% Discount", "10% Discount"]

print(np.select(cond, choice, default="No Discount"))

['No Discount' '5% Discount' '5% Discount' '10% Discount' '10% Discount'
 '10% Discount' 'No Discount' '5% Discount' '5% Discount' '10% Discount'
 'No Discount' 'No Discount']


import numpy as np

# ==================== NUMPY IMPLEMENTATIONS ====================

# 1. np.array()
# List se NumPy array banata hai.

# 2. type()
# Object ka data type check karta hai.

# 3. .dtype
# Array ke elements ka datatype batata hai.

# 4. .ndim
# Array ke dimensions (1D/2D/3D) ki ginti batata hai.

# 5. .size
# Array mein total elements ki ginti batata hai.

# 6. .sum()
# Sabhi elements ka total nikalta hai.

# 7. .shape
# Array ka structure batata hai, jaise rows aur columns.

# 8. .reshape()
# Array ka shape change karta hai, data same rehta hai.

# 9. np.eye()
# Identity matrix banata hai.

# 10. np.zeros()
# Zeros se filled array banata hai.

# 11. .std()
# Standard deviation nikalta hai, yani data kitna spread hai.

# 12. .var()
# Variance nikalta hai, yani data ke spread ka measure.

# 13. .copy()
# Original se independent array ki copy banata hai.

# 14. .sum(axis=0) / .sum(axis=1)
# axis=0 column-wise aur axis=1 row-wise sum karta hai.

# 15. .ravel()
# Array ko 1D karta hai aur generally view return karta hai.

# 16. .flatten()
# Array ko 1D karta hai aur independent copy return karta hai.

# 17. Boolean Masking (>, <, >=, <=, &, ~)
# Condition ke basis par array ke elements filter karta hai.

# 18. .transpose()
# Array ki rows aur columns swap karta hai.

# 19. Broadcasting (%, +, -, *, /)
# Array ke elements par element-wise operation apply karta hai.

# 20. np.where()
# Condition ke True/False result ke basis par values choose karta hai.

# 21. np.select()
# Multiple conditions ke basis par different values choose karta hai.